### ISSUE TITLE
This looks cool, what is this?

### ISSUE THREAD

**Issue by piegamesde** [jiegec/EspinalLib#1]
From what I can tell, you are making black box wrappers around ZipCPU library components and you are also re-implementing some of them in Spinal. I've also seen some pretty interesting stuff around `StreamFormal`. I'd really appreciate a few words of introduction in a `README` or something.

**Comment by jiegec** [comment]
Thanks! This repo contains some reusable hardware modules written in SpinalHDL for use in my research project.
